-- Complete Google Smart Home device types (82 total, inserting all missing ones)
INSERT INTO "google_action_types" ("name", "value") VALUES
  ('AC Unit',                  'action.devices.types.AC_UNIT'),
  ('Air Cooler',               'action.devices.types.AIRCOOLER'),
  ('Air Freshener',            'action.devices.types.AIRFRESHENER'),
  ('Air Purifier',             'action.devices.types.AIRPURIFIER'),
  ('AV Receiver',              'action.devices.types.AUDIO_VIDEO_RECEIVER'),
  ('Awning',                   'action.devices.types.AWNING'),
  ('Bathtub',                  'action.devices.types.BATHTUB'),
  ('Bed',                      'action.devices.types.BED'),
  ('Blanket',                  'action.devices.types.BLANKET'),
  ('Blender',                  'action.devices.types.BLENDER'),
  ('Boiler',                   'action.devices.types.BOILER'),
  ('Carbon Monoxide Detector', 'action.devices.types.CARBON_MONOXIDE_DETECTOR'),
  ('Charger',                  'action.devices.types.CHARGER'),
  ('Closet',                   'action.devices.types.CLOSET'),
  ('Coffee Maker',             'action.devices.types.COFFEE_MAKER'),
  ('Cooktop',                  'action.devices.types.COOKTOP'),
  ('Curtain',                  'action.devices.types.CURTAIN'),
  ('Dehumidifier',             'action.devices.types.DEHUMIDIFIER'),
  ('Dehydrator',               'action.devices.types.DEHYDRATOR'),
  ('Dishwasher',               'action.devices.types.DISHWASHER'),
  ('Doorbell',                 'action.devices.types.DOORBELL'),
  ('Drawer',                   'action.devices.types.DRAWER'),
  ('Dryer',                    'action.devices.types.DRYER'),
  ('Faucet',                   'action.devices.types.FAUCET'),
  ('Fireplace',                'action.devices.types.FIREPLACE'),
  ('Freezer',                  'action.devices.types.FREEZER'),
  ('Fryer',                    'action.devices.types.FRYER'),
  ('Game Console',             'action.devices.types.GAME_CONSOLE'),
  ('Gate',                     'action.devices.types.GATE'),
  ('Grill',                    'action.devices.types.GRILL'),
  ('Hood',                     'action.devices.types.HOOD'),
  ('Humidifier',               'action.devices.types.HUMIDIFIER'),
  ('Kettle',                   'action.devices.types.KETTLE'),
  ('Microwave',                'action.devices.types.MICROWAVE'),
  ('Mop',                      'action.devices.types.MOP'),
  ('Mower',                    'action.devices.types.MOWER'),
  ('Multicooker',              'action.devices.types.MULTICOOKER'),
  ('Network',                  'action.devices.types.NETWORK'),
  ('Oven',                     'action.devices.types.OVEN'),
  ('Pergola',                  'action.devices.types.PERGOLA'),
  ('Pet Feeder',               'action.devices.types.PETFEEDER'),
  ('Pressure Cooker',          'action.devices.types.PRESSURECOOKER'),
  ('Pump',                     'action.devices.types.PUMP'),
  ('Radiator',                 'action.devices.types.RADIATOR'),
  ('Refrigerator',             'action.devices.types.REFRIGERATOR'),
  ('Remote Control',           'action.devices.types.REMOTECONTROL'),
  ('Router',                   'action.devices.types.ROUTER'),
  ('Scene',                    'action.devices.types.SCENE'),
  ('Security System',          'action.devices.types.SECURITYSYSTEM'),
  ('Set-Top Box',              'action.devices.types.SETTOP'),
  ('Shower',                   'action.devices.types.SHOWER'),
  ('Shutter',                  'action.devices.types.SHUTTER'),
  ('Smoke Detector',           'action.devices.types.SMOKE_DETECTOR'),
  ('Soundbar',                 'action.devices.types.SOUNDBAR'),
  ('Sous Vide',                'action.devices.types.SOUSVIDE'),
  ('Speaker',                  'action.devices.types.SPEAKER'),
  ('Stand Mixer',              'action.devices.types.STANDMIXER'),
  ('Streaming Box',            'action.devices.types.STREAMING_BOX'),
  ('Streaming Soundbar',       'action.devices.types.STREAMING_SOUNDBAR'),
  ('Streaming Stick',          'action.devices.types.STREAMING_STICK'),
  ('Television',               'action.devices.types.TV'),
  ('Vacuum',                   'action.devices.types.VACUUM'),
  ('Valve',                    'action.devices.types.VALVE'),
  ('Washer',                   'action.devices.types.WASHER'),
  ('Water Heater',             'action.devices.types.WATERHEATER'),
  ('Water Purifier',           'action.devices.types.WATERPURIFIER'),
  ('Water Softener',           'action.devices.types.WATERSOFTENER'),
  ('Window',                   'action.devices.types.WINDOW'),
  ('Yogurt Maker',             'action.devices.types.YOGURTMAKER')
ON CONFLICT ("value") DO NOTHING;

-- Complete Google Smart Home traits (38 total, inserting all missing ones)
INSERT INTO "google_device_traits" ("name", "value") VALUES
  ('App Selector',        'action.devices.traits.AppSelector'),
  ('Arm / Disarm',        'action.devices.traits.ArmDisarm'),
  ('Channel',             'action.devices.traits.Channel'),
  ('Cook',                'action.devices.traits.Cook'),
  ('Dispense',            'action.devices.traits.Dispense'),
  ('Dock',                'action.devices.traits.Dock'),
  ('Energy Storage',      'action.devices.traits.EnergyStorage'),
  ('Fill',                'action.devices.traits.Fill'),
  ('Input Selector',      'action.devices.traits.InputSelector'),
  ('Light Effects',       'action.devices.traits.LightEffects'),
  ('Locator',             'action.devices.traits.Locator'),
  ('Media State',         'action.devices.traits.MediaState'),
  ('Modes',               'action.devices.traits.Modes'),
  ('Network Control',     'action.devices.traits.NetworkControl'),
  ('Object Detection',    'action.devices.traits.ObjectDetection'),
  ('Occupancy Sensing',   'action.devices.traits.OccupancySensing'),
  ('Reboot',              'action.devices.traits.Reboot'),
  ('Rotation',            'action.devices.traits.Rotation'),
  ('Run Cycle',           'action.devices.traits.RunCycle'),
  ('Scene',               'action.devices.traits.Scene'),
  ('Sensor State',        'action.devices.traits.SensorState'),
  ('Software Update',     'action.devices.traits.SoftwareUpdate'),
  ('Status Report',       'action.devices.traits.StatusReport'),
  ('Temperature Control', 'action.devices.traits.TemperatureControl'),
  ('Timer',               'action.devices.traits.Timer'),
  ('Toggles',             'action.devices.traits.Toggles'),
  ('Transport Control',   'action.devices.traits.TransportControl'),
  ('Volume',              'action.devices.traits.Volume')
ON CONFLICT ("value") DO NOTHING;
