#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$DB_USER" --dbname "$DB_NAME" <<-EOSQL
    GRANT SELECT , INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PUBLIC TO ${BACKEND_DB_USER};
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA PUBLIC TO ${BACKEND_DB_USER};

EOSQL
